### ISSUE TITLE
Support for Ansible 2.0

### ISSUE THREAD

**Issue by Dude4Linux** [Gu1/ansible-lxc-remote#5]
@Gu1 do you have plans to support Ansible 2.0?  I would like to include your software in the next release of the TurnKey GNU/Linux Ansible appliance for managing containers on a TurnKey LXC appliance.

**Comment by ser** [comment]
+1

**Comment by hachi** [comment]
@ser @Dude4Linux https://github.com/chifflier/ansible-lxc-ssh does this same job and is compatible with ansible 2.0

**Comment by Dude4Linux** [comment]
@hachi Thanks for the headsup :)  This is exactly what I was looking for.  Only problem is it's not backward compatible with Ansible 1.9.x and it doesn't work in my setup (doesn't pass the container name to lxc-attach).  Still it's a good start.

**Comment by Dude4Linux** [comment]
MyBad.  As soon as I forked the repository, I saw the note about needing to specify the container name as an extra arg.  Don't know how I missed that the first try.  With the added argument in the inventory file it works with my setup.
